# Generated by Django 2.0.4 on 2018-04-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('gifted', models.CharField(max_length=250)),
                ('hobby', models.CharField(max_length=250)),
                ('desire', models.CharField(max_length=250)),
            ],
        ),
    ]
